version: '3.8'

services:
  # database containers, one for each db
  postgres_site:
    container_name: postgres_site
    # command:
    #   - "postgres"
    #   - "-c"
    #   - "max_connections=200"
    #   # SOLUÇÃO PARA O ERRO DE CONEXÕES IDLE ATIVAS
    #   # SELECT * FROM pg_stat_activity;
    #   # SHOW idle_in_transaction_session_timeout
    #   - "-c"
    #   - "idle_in_transaction_session_timeout=6000"
    restart: unless-stopped
    image: postgres:latest
    # ports:
    #   - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ../../.env
    networks:
      - nginx_network

  pgbouncer:
    image: edoburu/pgbouncer
    env_file:
      - ../../.env
    ports:
      - "5432:5432"
    depends_on:
      - postgres_site
    networks:
      - nginx_network

networks:
  nginx_network:
    name: rede_nginx

volumes:
  pgdata: